### ISSUE TITLE
[Suggestions] Will you please add multimedia protocol support？

### ISSUE THREAD

**Issue by zxp19821005** [ricmsd/flexplayer#1]
First , thansk to develop the program.
I've ported it to ArchLinux AUR : https://aur.archlinux.org/packages/flexplayer
Will you please add multimedia protocol support , such as udp/rtsp/rtmp/hls/http/https and so on ?
Thanks a lot.
My English level is very poor, please forgive me a lot.

**Comment by ricmsd** [comment]
Thanks for your interest in flexplayer.

Since flexplayer is an electron app, it seems to me that it could easily support media that chrome natively supports. Also, I think hls can be supported using a JavaScript library (hls.js).

I'm not familiar with udp/rtsp/rtmp, so I did a little research, but I didn't think it would be possible to support these.

So, for example, I can probably implement a feature where you press Ctrl-N and type in an mp4 or m3u8 URL(http/https) and a video will be added to the grid. Does this match your image?

By the way, my level of English is also poor and I am writing this text while translating.

**Comment by zxp19821005** [comment]
Thanks a lot for your reply.I will try it later.
